apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental-app
  template:
    metadata:
      labels:
        app: rental-app
    spec:
      containers:
        - name: rental-app
          image: anakadic/rental-app:2
          ports:
            - containerPort: 8080

